module.exports.SOCKET_EVENT = Object.freeze({
  P2P_EMIT: 'P2P_EMIT',
  P2P_EMIT_ACKNOWLEDGE: 'P2P_EMIT_ACKNOWLEDGE',
  P2P_REGISTER: 'P2P_REGISTER',
  P2P_UNREGISTER: 'P2P_UNREGISTER',
  P2P_REGISTER_SUCCESS: 'P2P_REGISTER_SUCCESS',
  P2P_REGISTER_FAILED: 'P2P_REGISTER_FAILED',
  P2P_DISCONNECT: 'P2P_DISCONNECT',
  LIST_CLIENTS: 'LIST_CLIENTS',
  SERVER_ERROR: 'SERVER_ERROR',
  // Stream events
  P2P_EMIT_STREAM: 'P2P_EMIT_STREAM',
});

module.exports.SERVER_CONFIG = Object.freeze({
  IP_ADDRESS: 'localhost',
  PORT: 9001,
});
