module.exports.SOCKET_EVENT = Object.freeze({
  // Core API events
  JOIN_ROOM: 'JOIN_ROOM',
  EMIT_ROOM: 'EMIT_ROOM',
  // Message API events
  P2P_EMIT: 'P2P_EMIT',
  P2P_EMIT_ACKNOWLEDGE: 'P2P_EMIT_ACKNOWLEDGE',
  P2P_REGISTER: 'P2P_REGISTER',
  P2P_UNREGISTER: 'P2P_UNREGISTER',
  P2P_DISCONNECT: 'P2P_DISCONNECT',
  LIST_CLIENTS: 'LIST_CLIENTS',
  SERVER_ERROR: 'SERVER_ERROR',
  // Stream API events
  P2P_REGISTER_STREAM: 'P2P_REGISTER_STREAM',
  P2P_EMIT_STREAM: 'P2P_EMIT_STREAM',
  // Multi-target Message API events
  MULTI_API_ADD_TARGET: 'MULTI_API_ADD_TARGET',
  MULTI_API_TARGET_DISCONNECT: 'MULTI_API_TARGET_DISCONNECT',
  CLIENT_IDENTIFIER_PREFIX: '-from-client-',
  // Multi-target Stream API events
  MULTI_API_CREATE_STREAM: 'MULTI_API_CREATE_STREAM',
  PEER_STREAM_DESTROYED: 'PEER_STREAM_DESTROYED',
  STREAM_IDENTIFIER_PREFIX: '-from-stream-',
  // Service API
  P2P_EMIT_SERVICE: 'P2P_EMIT_SERVICE',
  P2P_EMIT_SERVICE_ACKNOWLEDGE: 'P2P_EMIT_SERVICE_ACKNOWLEDGE',
});

module.exports.SERVER_CONFIG = Object.freeze({
  IP_ADDRESS: 'localhost',
  PORT: 9001,
});

module.exports.SOCKET_EVENT_ACTION = Object.freeze({
  PUBLISH_SERVICE: 'PUBLISH_SERVICE',
  SUBSCRIBE_CLIENT: 'SUBSCRIBE_CLIENT',
});
