module.exports.SOCKET_EVENT = Object.freeze({
  P2P_EMIT: 'P2P_EMIT',
  P2P_EMIT_ACKNOWLEDGE: 'P2P_EMIT_ACKNOWLEDGE',
  P2P_REGISTER: 'P2P_REGISTER',
  P2P_REGISTER_ACKNOWLEDGED: 'P2P_REGISTER_ACKNOWLEDGED',
  P2P_DISCONNECT: 'P2P_DISCONNECT',
});

module.exports.SERVER_CONFIG = Object.freeze({
  PORT: 8889,
});
